version: '{build}'
image: Visual Studio 2017
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: off
build_script:
- ps: ./build.ps1
on_success:
- sh: >-
    curl -s https://codecov.io/bash > codecov
    chmod +x codecov
    ./codecov -f *opencover.xml
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: '{version}'
  package_version: '{version}'
artifacts:
- path: '**\*.nupkg'
